// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1638432376);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1638436093);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1638436123);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 1046);
user_pref("browser.cache.disk.capacity", 829440);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "4865a37f-67a2-4416-b481-32a1442ca79c");
user_pref("calendar.registry.4865a37f-67a2-4416-b481-32a1442ca79c.calendar-main-in-composite", true);
user_pref("calendar.registry.4865a37f-67a2-4416-b481-32a1442ca79c.disabled", true);
user_pref("calendar.registry.4865a37f-67a2-4416-b481-32a1442ca79c.name", "Casa");
user_pref("calendar.registry.4865a37f-67a2-4416-b481-32a1442ca79c.type", "storage");
user_pref("calendar.registry.4865a37f-67a2-4416-b481-32a1442ca79c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Madrid");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1638432363782");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210901192859");
user_pref("extensions.lastAppVersion", "78.14.0");
user_pref("extensions.lastPlatformVersion", "78.14.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"093e5b7d-f1d4-4f4c-8cbe-18f1f8a0f8a1\",\"google@search.mozilla.org\":\"c185b6db-5be8-4c60-bb69-6254f71a81aa\",\"bing@search.mozilla.org\":\"a87b8b6a-9198-4621-abdc-ae9247bb532d\",\"drae@search.mozilla.org\":\"ff82b437-35bb-467a-928e-7e7a949036a5\",\"ddg@search.mozilla.org\":\"a89935a9-3d57-4206-97f3-9f9ee6461ff2\",\"wikipedia@search.mozilla.org\":\"b8db0233-3d1f-442d-9143-fe018691477e\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "22ab4aff-4f0b-497b-b46a-5f9a72d3a9e");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.14.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "42e96441-53cd-45a2-b092-46454d178af3");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1638432706500\"");
user_pref("services.settings.last_update_seconds", 1638436092);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1638436092);
user_pref("services.settings.main.hijack-blocklists.last_check", 1638436092);
user_pref("services.settings.main.language-dictionaries.last_check", 1638436092);
user_pref("services.settings.main.search-config.last_check", 1638436092);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1638436092);
user_pref("services.settings.main.sites-classification.last_check", 1638436092);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1638436092);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "32fc086a-672b-4108-85a4-b0f1ba37397a");
user_pref("toolkit.telemetry.previousBuildID", "20210901192859");
